export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST" 
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL" 
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS" 

export const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST" 
export const ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL" 
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS" 
