export const COMPANIES_NAMES_REQUEST = "COMPANIES_NAMES_REQUET"
export const COMPANIES_NAMES_FAIL = "COMPANIES_NAMES_FAIL" 
export const COMPANIES_NAMES_SUCCESS = "COMPANIES_NAMES_SUCCESS" 

export const COMPANY_CLIENTS_REQUEST = "COMPANY_CLIENTS_REQUEST" 
export const COMPANY_CLIENTS_FAIL = "COMPANY_CLIENTS_FAIL" 
export const COMPANY_CLIENTS_SUCCESS = "COMPANY_CLIENTS_SUCCESS" 